apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-1-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-1
      labels:
        app: kafka
        server-id: "1"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-1
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-1
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: a924f1bae11ae11e9aeee0223d8dd6d6-1882987397.us-east-2.elb.amazonaws.com
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "50000000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "100000000"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "50000000"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
      nodeSelector:
        custom/node-id: "1" 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-2-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-2
      labels:
        app: kafka
        server-id: "2"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-2
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-2
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: a928602fb11ae11e9aeee0223d8dd6d6-813979459.us-east-2.elb.amazonaws.com
            - name: KAFKA_ADVERTISED_PORT
              value: "9093"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "50000000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "100000000"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "50000000"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
      nodeSelector:
        custom/node-id: "2" 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-3-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-3
      labels:
        app: kafka
        server-id: "3"
    spec:
      volumes:
        - name: data
          gcePersistentDisk:
            pdName: kafka-3
            fsType: ext4
      containers:
        - name: server
          image: wurstmeister/kafka:latest
          env:
            - name: KAFKA_LOG_DIRS
              value: /kafka/kafka-3
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_CREATE_TOPICS
              value: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: a92c2b76411ae11e9aeee0223d8dd6d6-394070084.us-east-2.elb.amazonaws.com
            - name: KAFKA_ADVERTISED_PORT
              value: "9094"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "50000000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "100000000"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "50000000"
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /kafka
              name: data
      nodeSelector:
        custom/node-id: "3" 
